# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[flavor]
use = "catppuccin-macchiato"

[manager]
ratio = [2, 5, 3]
show_hidden = true

[opener]
edit = [
  { run = 'export NVIM_APPNAME=AstroNvim; nvim "$@"', desc = "nvim", block = true }
]

[preview]
max_width  = 1000
max_height = 1000
