#!/usr/bin/env bash

#          ╭──────────────────────────────────────────────────────────╮
#          │                    Scripting addition                    │
#          ╰──────────────────────────────────────────────────────────╯
# Wiki page:
#  - https://github.com/asmvik/yabai/wiki/Installing-yabai-(from-HEAD)#configure-scripting-addition

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

#          ╭──────────────────────────────────────────────────────────╮
#          │                     Global Settings                      │
#          ╰──────────────────────────────────────────────────────────╯
# References:
#  - https://github.com/asmvik/yabai/wiki/Configuration#configuration-file
#  - https://github.com/asmvik/yabai/blob/master/examples/yabairc
#  - https://github.com/asmvik/yabai/blob/master/doc/yabai.asciidoc

# Padding and Gaps
PADDING=10
yabai -m config \
  top_padding $PADDING \
  bottom_padding $PADDING \
  left_padding $PADDING \
  right_padding $PADDING \
  window_gap 10

# Status Bar
yabai -m config external_bar all:32:0

# Defaults
yabai -m config \
  menubar_opacity 1.0 \
  mouse_follows_focus off \
  focus_follows_mouse off \
  display_arrangement_order default \
  window_origin_display default \
  window_placement second_child \
  window_insertion_point focused \
  window_zoom_persist on \
  window_shadow on \
  window_animation_duration 0.0 \
  window_animation_easing ease_out_circ \
  window_opacity_duration 0.0 \
  active_window_opacity 1.0 \
  normal_window_opacity 0.90 \
  window_opacity off \
  insert_feedback_color 0xffd75f5f \
  split_ratio 0.50 \
  split_type auto \
  auto_balance off \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap

#          ╭──────────────────────────────────────────────────────────╮
#          │                          Spaces                          │
#          ╰──────────────────────────────────────────────────────────╯

# yabai -m config layout float
# yabai -m config layout bsp
yabai -m config layout stack

yabai -m space 1 --label main
yabai -m space 2 --label terminal --layout bsp
yabai -m space 3 --label communication
yabai -m space 4 --label media

#          ╭──────────────────────────────────────────────────────────╮
#          │                           Apps                           │
#          ╰──────────────────────────────────────────────────────────╯
# yabai -m query --windows | jq '.[] | {app: .app, title: .title }'
# sticky: keep window on all spaces
# grid=<rows>:<cols>:<start-x>:<start-y>:<width>:<height>

# https://github.com/asmvik/yabai/issues/1929
yabai -m rule --add app=".*" sub-layer=normal

# System Apps
yabai -m rule --add app="(System Preferences|系统设置)" manage=off grid=4:6:2:0:2:3
yabai -m rule --add app="(Finder|访达)" manage=off sticky=on grid=20:20:1:1:18:18
yabai -m rule --add app="(Preview|预览)" manage=off
yabai -m rule --add app="(Music|音乐)" manage=off space=media grid=10:10:1:1:8:8
yabai -m rule --add app="(Calendar|日历)" manage=off grid=10:10:1:1:8:8

# GUI Apps
yabai -m rule --add app="(Eudic|欧路词典)" manage=off sticky=on grid=10:10:1:1:8:8
yabai -m rule --add app="微信" manage=off space=communication grid=8:5:1:1:3:6
yabai -m rule --add app="微信" title="^(视频通话.*)$" manage=off space=communication
yabai -m rule --add app="Raycast" manage=off
yabai -m rule --add app="Emby" manage=off space=media

# TUI Apps
yabai -m rule --add app="kitty" title="^S:yazi$" manage=off
yabai -m rule --add app="kitty" title="^S:sticky-notes$" manage=off space=main
yabai -m signal --add event=window_destroyed label="sticky-notes-closed" app="kitty" action="if [[ \$(yabai -m query --windows | jq -r '[.[] | select(.app==\"kitty\" and .title==\"S:sticky-notes\")][0].id') == null ]]; then yabai -m config --space main right_padding $PADDING; fi"

# Apply rules
yabai -m rule --apply

#          ╭──────────────────────────────────────────────────────────╮
#          │                          Signal                          │
#          ╰──────────────────────────────────────────────────────────╯

yabai -m signal --add event=window_moved action="yabai -m window --focus \$YABAI_WINDOW_ID"

echo "yabai configuration loaded.."
