# https://sw.kovidgoyal.net/kitty/conf/

# ── Fonts ─────────────────────────────────────────────────────────────
# `kitten choose-fonts`
font_family Maple Mono NF CN
font_size 16
disable_ligatures cursor
# https://font.subf.dev/en/playground/
font_features MapleMono-NF-CN-Regular +cv01 +ss05
font_features MapleMono-NF-CN-SemiBold +cv01 +ss05
font_features MapleMono-NF-CN-Italic +cv01 +ss05
font_features MapleMono-NF-CN-SemiBoldItalic +cv01 +ss05

# ── Text cursor customization ─────────────────────────────────────────
cursor_trail 20
cursor_trail_decay 0.0 0.3
cursor_trail_start_threshold 10

# ── Scrollback ────────────────────────────────────────────────────────

# ── Mouse ─────────────────────────────────────────────────────────────
copy_on_select true

# ── Performance tuning ────────────────────────────────────────────────
sync_to_monitor no

# ── Terminal bell ─────────────────────────────────────────────────────

# ── Window layout ─────────────────────────────────────────────────────
remember_window_position true
enabled_layouts splits,stack
hide_window_decorations titlebar-only

# ── Tab bar ───────────────────────────────────────────────────────────
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style angled
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{title}{' ' if layout_name == 'stack' else ''}"

# ── Color scheme ──────────────────────────────────────────────────────
background_opacity 0.8
background_blur 30

# ── Advanced ──────────────────────────────────────────────────────────
allow_remote_control true

# ── OS specific tweaks ────────────────────────────────────────────────
macos_option_as_alt both

