# ╭──────────────────────────────────────────────────────────╮
# │                    Keyboard shortcuts                    │
# ╰──────────────────────────────────────────────────────────╯
# Configa: https://sw.kovidgoyal.net/kitty/conf/#keyboard-shortcuts
# Guide:   https://sw.kovidgoyal.net/kitty/mapping/
# Actions: https://sw.kovidgoyal.net/kitty/actions/
# `ctrl+shift+f3` to run the command palette
kitty_mod ctrl+shift

# ── Clipboard ─────────────────────────────────────────────────────────

# ── Scrolling ─────────────────────────────────────────────────────────

# ── Window management ─────────────────────────────────────────────────
# https://sw.kovidgoyal.net/kitty/launch/
map cmd+shift+- launch --location=hsplit --cwd=current
map cmd+shift+\ launch --location=vsplit --cwd=current
map cmd+shift+t launch --type=tab --cwd=current
# Resize, default `ctrl+shift+r` / `cmd+r`
map cmd+shift+h kitten relative_resize.py left
map cmd+shift+j kitten relative_resize.py down
map cmd+shift+k kitten relative_resize.py up
map cmd+shift+l kitten relative_resize.py right

# ── Tab management ────────────────────────────────────────────────────
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

# ── Layout management ─────────────────────────────────────────────────
map cmd+z combine : toggle_layout stack : scroll_prompt_to_bottom

# ── Font sizes ────────────────────────────────────────────────────────

# ── Select and act on visible text ────────────────────────────────────

# ── Miscellaneous ─────────────────────────────────────────────────────
# nvim
map cmd+s  send_text all \e:w\r

# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten '/Users/yuchenfei/.local/share/nvim/site/pack/core/opt/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py'
# Browse scrollback buffer in nvim
map kitty_mod+h kitty_scrollback_nvim
# Browse output of the last shell command in nvim
map kitty_mod+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output
# Show clicked command output in nvim
mouse_map ctrl+shift+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output
