#!/usr/bin/env lua

-- https://github.com/FelixKratz/SketchyBar
-- https://github.com/FelixKratz/SbarLua
-- https://github.com/FelixKratz/dotfiles

-- Add the current directory to the Lua search path
package.path = "./?.lua;./?/init.lua;./?/?.lua;" .. package.path

-- Require the sketchybar module
Sbar = require("sketchybar")

-- Bundle the entire initial configuration into a single message to sketchybar
-- This improves startup times drastically, try removing both the begin and end
-- config calls to see the difference -- yeah..
Sbar.begin_config()
require("bar")
require("default")
require("items")
Sbar.hotload(true)
Sbar.end_config()

-- Run the event loop of the sketchybar module (without this there will be no
-- callback functions executed in the lua module)
Sbar.event_loop()
